### ISSUE TITLE
Put docs on ReadTheDocs

### ISSUE THREAD

**Issue by dan-blanchard** [MaxPoint/spylon#15]
Would be nice if you didn't have to build the docs yourself.

**Comment by mariusvniekerk** [comment]
Yeah,  was thinking of doing it with doctr

**Comment by parente** [comment]
Do we need to build the docs on travis? Would the typical readthedocs.yml work along with the RTD github hook?

Here's a sample that uses a conda env: https://github.com/jupyter/kernel_gateway/blob/master/readthedocs.yml

**Comment by mariusvniekerk** [comment]
Trying doctr but rtd is probably okay.

**Comment by mariusvniekerk** [comment]
The other advantage is that we can make travis fail if for some reason the docs don't build.  

Getting the docs to build probably requires an apache spark install and a SPARK_HOME, so there is that...

**Comment by mariusvniekerk** [comment]
Docs are now built and pushed to https://maxpoint.github.io/spylon/

**Comment by dan-blanchard** [comment]
Awesome. Thanks Marius!
